version: "3.8"

services:
  backend:
    image: php:8.3-fpm
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - 9000
    working_dir: /var/www/html
    command: >
      sh -c "apt-get update && apt-get install -y git zip unzip && 
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      composer install &&
      php-fpm"
    networks:
      - app-network

  frontend:
    image: node:16
    container_name: frontend
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
    expose:
      - 8080
    command: sh -c "npm install && npm run build && npm run serve"
    networks:
      - app-network

  webserver:
    image: nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
